/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    {
      type: "category",
      label: "analysis",
      items: [ {
        type: 'autogenerated',
        dirName: 'analysis',
      },],
    },
    {
      type: "category",
      label: "bestPractices",
      items: [ {
        type: 'autogenerated',
        dirName: 'good-practices',
      },],
    },
    {
      type: "category",
      label: "career",
      items: [ {
        type: 'autogenerated',
        dirName: 'career',
      },],
    },
  ],
};

module.exports = sidebars;
