backend:
  name: github
  branch: main
  repo: AlanSecundo/docusaurus-decap-cms


# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

publish_mode: editorial_workflow

i18n:
  structure: multiple_folders
  locales: [pt, en, es]
  default_locale: en

collections:
  - name: analysis
    label: "Análise"
    i18n: true
    folder: docs/analysis
    identifier_field: title
    extension: md
    widget: "list"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: docs/analysis/{{year}}/{{month}}/{{title}}
    preview_path_date_field: published_at
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - { name: title, label: Title, widget: string, i18n: true }
      - { name: body, label: Body, widget: markdown, i18n: true }
  - name: bestPractices
    label: "Boas práticas"
    i18n: true
    folder: docs/good-practices
    identifier_field: title
    extension: md
    widget: "list"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: docs/good-practices/{{year}}/{{month}}/{{title}}
    preview_path_date_field: published_at
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - { name: title, label: Title, widget: string, i18n: true }
      - { name: body, label: Body, widget: markdown, i18n: true }
  - name: career
    label: "Carreira"
    i18n: true
    folder: docs/career
    identifier_field: title
    extension: md
    widget: "list"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: docs/career/{{year}}/{{month}}/{{title}}
    preview_path_date_field: published_at
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - { name: title, label: Title, widget: string, i18n: true }
      - { name: body, label: Body, widget: markdown, i18n: true }
